import type { Client, Message, Role } from "discord.js";
import fetch from "node-fetch";

const endpoint = "https://www.thecolorapi.com/id?hex=";

export const pickColor = async (client: Client, msg: Message, color?: string) => {
    let random = false;
    color = (color || "").replace("#", "").trim();
    if (!color) {
        color = Math.floor(Math.random() * 16777215).toString(16).padStart(6, "0");
        random = true;
    }
    color = color.toUpperCase();
    const resp = await fetch(`${endpoint}${color}`);
    const colorInfo = await resp.json();
    const name = colorInfo.name.value + " (Color)";
    if (random) {
        color = colorInfo.name.closest_named_hex;
    } else {
        color = `#${color}`;
    }

    const guild = msg.guild!;
    let role: Role;
    if (guild.roles.cache.some((role) => role.color.toString(16).toUpperCase() === color)) {
        role = guild.roles.cache.find((role) => role.color.toString(16).toUpperCase() === color)!;
    } else {
        role = await guild.roles.create({
            data: {
                name,
                color,
                position: guild.roles.cache.size - 5
            },
            reason: "Autogenerated color role"
        });
    }

    msg.member!.roles.cache.forEach((role) => {
        if (role.name.indexOf(" (Color)") > 0) {
            msg.reply(`Removing role "${role.name}" with color #${role.color.toString(16).toUpperCase()}`);
            msg.member!.roles.remove(role);
        }
    });
    msg.member!.roles.add(role);
    return `Adding role ${name} with color ${color} :paintbrush:`;
};

export default pickColor;

